# Generated by Django 5.1 on 2025-03-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0006_alter_chatroom_unique_together_chatroom_custom_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='custom_name',
        ),
        migrations.CreateModel(
            name='ChatRoomName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=100)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_names', to='hamroapp.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat_room', 'user')},
            },
        ),
    ]
