# Generated by Django 5.1 on 2025-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0007_remove_chatroom_custom_name_chatroomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
