# Generated by Django 5.1 on 2025-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0008_complaint_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='custom_sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
