# Generated by Django 5.1 on 2025-04-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0011_user_created_at_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_rent_increase',
            field=models.IntegerField(default=0),
        ),
    ]
