# Generated by Django 5.1 on 2025-04-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0012_room_last_rent_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='last_rent_increase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
