# Generated by Django 5.1 on 2025-04-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0013_alter_room_last_rent_increase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_salary_increase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='AdminSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stripe_payment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=50)),
                ('subscription_year', models.IntegerField(help_text='Year the subscription covers')),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('superadmin', models.ForeignKey(limit_choices_to={'role': 'superadmin'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stripe_payment_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='failed', max_length=50)),
                ('payment_year', models.IntegerField(help_text='Year the payment covers')),
                ('payment_end_date', models.DateField(blank=True, null=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='security_payments_made', to=settings.AUTH_USER_MODEL)),
                ('security', models.ForeignKey(limit_choices_to={'role': 'security'}, on_delete=django.db.models.deletion.CASCADE, related_name='security_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
