# Generated by Django 5.1 on 2025-04-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0014_user_last_salary_increase_user_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
