# Generated by Django 5.1 on 2026-04-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0010_bill_payment_status'),
        ('hamroapp', '0019_bill_billitem'),
    ]

    operations = [
    ]
