# Generated by Django 5.1 on 2026-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamroapp', '0021_alter_bill_id_alter_billitem_id_alter_visitor_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitypayment',
            name='payment_month',
            field=models.IntegerField(blank=True, help_text='Month (1-12) the payment covers', null=True),
        ),
    ]
